const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict');
const source=fs.readFileSync('app.js','utf8');
const elements=new Proxy({}, {get:(target,id)=>target[id] ||= {value:'',innerHTML:'',classList:{add(){},remove(){}}}});
let saved;const stop=new Error('captured payload');
const ctx=vm.createContext({document:{getElementById:id=>elements[id]},recordNameAvailable:async()=>true,withRecordSaveLock:async(_table,save)=>save(),requireAdmin:()=>true,requireLogin:()=>true,uploadFileToSupabase:async()=>null,db:{from:()=>({insert(data){saved=data[0];throw stop},update(data){saved=data;throw stop}})}});
vm.runInContext(source.slice(source.indexOf('async function addCase()'),source.indexOf('async function deleteCase(')),ctx);
vm.runInContext(source.slice(source.indexOf('async function saveCaseUpdate()'),source.indexOf('async function saveCaseUpdate()')+source.slice(source.indexOf('async function saveCaseUpdate()')).indexOf('\nasync function ',10)),ctx);
(async()=>{elements.caseName.value='Test';elements.clientRole.value='  مجني عليه  ';elements.opponentRole.value='متهم';await assert.rejects(ctx.addCase(),e=>e===stop);assert.equal(saved.client_role,'مجني عليه');assert.equal(saved.opponent_role,'متهم');elements.editCaseName.value='Test';elements.editClientRole.value='مدعي';elements.editOpponentRole.value='  مدعى عليه ';await assert.rejects(ctx.saveCaseUpdate(),e=>e===stop);assert.equal(saved.client_role,'مدعي');assert.equal(saved.opponent_role,'مدعى عليه');elements.editClientRole.value='';elements.editOpponentRole.value='';await assert.rejects(ctx.saveCaseUpdate(),e=>e===stop);assert.equal(saved.client_role,'');assert.equal(saved.opponent_role,'');console.log('PASS: add/update payloads, trim and clearing optional roles');})().catch(e=>{console.error(e);process.exitCode=1});

