const {chromium}=require('C:/Users/Ahmed Nabih/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
const {pathToFileURL}=require('node:url');
const path=require('node:path');
(async()=>{
const browser=await chromium.launch({headless:true,channel:'msedge'});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*supabase*/**',r=>{throw Error('Preview attempted live database access')});
await page.goto(pathToFileURL(path.resolve('preview/index.html')).href);
await page.locator('.agenda-row').first().waitFor();
assert.equal(await page.locator('.agenda-row').count(),2);
assert.equal(await page.locator('.priority-item').count(),2);
await page.screenshot({path:'preview/dashboard-desktop.png',fullPage:true});
await page.locator('#officeSearch').fill('عمر');assert.equal(await page.locator('.case-card').count(),1);
await page.locator('#officeSearch').fill('');
await page.locator('.case-card').first().click();
await page.locator('.case-timeline').waitFor();
assert.equal(await page.locator('.timeline-event').count(),2);
await page.screenshot({path:'preview/case-desktop.png',fullPage:true});
await page.keyboard.press('Escape');assert.equal(await page.locator('.case-workspace').count(),0);
await page.setViewportSize({width:390,height:844});
assert.ok(await page.locator('.mobile-dock').isVisible());
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'preview/dashboard-mobile.png',fullPage:true});
await page.locator('.case-card').first().click();
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'preview/case-mobile.png',fullPage:true});
await page.keyboard.press('Escape');
await page.getByRole('button',{name:'القادمة',exact:true}).click();assert.equal(await page.locator('.agenda-row').count(),0);
await page.evaluate(()=>{allCasesCache[0].name='<img src=x onerror=alert(1)>';updateOfficeTasks([])});
assert.equal(await page.locator('.case-card img').count(),0);
assert.deepEqual(errors,[]);
await browser.close();console.log('PASS: agenda, priorities, search, case timeline, escape, mobile layout, empty state, escaping; no live data.');
})().catch(e=>{console.error(e);process.exit(1)});
