-- Run once in the SQL editor of the existing Supabase project.
-- Matches company_id to the actual type of public.companies.id.
begin;
do $$
declare company_id_type text;
begin
  select format_type(a.atttypid, a.atttypmod) into company_id_type
  from pg_attribute a where a.attrelid = 'public.companies'::regclass
    and a.attname = 'id' and not a.attisdropped;
  if company_id_type is null then raise exception 'companies.id is missing'; end if;
  execute format('create table if not exists public.company_tasks (
    id bigint generated by default as identity primary key,
    company_id %s not null references public.companies(id) on delete cascade,
    title text not null check (char_length(btrim(title)) between 1 and 250),
    description text not null default '''' check (char_length(description) <= 5000),
    due_date date not null,
    completed boolean not null default false,
    created_by uuid references auth.users(id) on delete set null default auth.uid(),
    created_at timestamptz not null default now()
  )', company_id_type);
end $$;
create index if not exists company_tasks_company_due_idx on public.company_tasks(company_id, due_date);
alter table public.company_tasks enable row level security;
revoke all on public.company_tasks from anon;
grant select, insert, update, delete on public.company_tasks to authenticated;
grant usage, select on sequence public.company_tasks_id_seq to authenticated;

drop policy if exists company_tasks_read on public.company_tasks;
create policy company_tasks_read on public.company_tasks for select to authenticated
using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.status = 'approved')
  and exists (select 1 from public.companies c where c.id = company_tasks.company_id)
);
drop policy if exists company_tasks_insert on public.company_tasks;
create policy company_tasks_insert on public.company_tasks for insert to authenticated
with check (
  created_by = auth.uid()
  and exists (select 1 from public.profiles p where p.id = auth.uid() and p.status = 'approved' and p.role in ('admin', 'employee'))
  and exists (select 1 from public.companies c where c.id = company_tasks.company_id)
);
drop policy if exists company_tasks_update on public.company_tasks;
create policy company_tasks_update on public.company_tasks for update to authenticated
using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.status = 'approved' and p.role in ('admin', 'employee'))
  and exists (select 1 from public.companies c where c.id = company_tasks.company_id)
) with check (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.status = 'approved' and p.role in ('admin', 'employee'))
  and exists (select 1 from public.companies c where c.id = company_tasks.company_id)
);
drop policy if exists company_tasks_delete on public.company_tasks;
create policy company_tasks_delete on public.company_tasks for delete to authenticated
using (
  exists (select 1 from public.profiles p where p.id = auth.uid() and p.status = 'approved' and p.role in ('admin', 'employee'))
  and exists (select 1 from public.companies c where c.id = company_tasks.company_id)
);
commit;
